name: 'Gem Dependency Updater'
description: 'Updates the Gemfile and Gemfile.lock in a dependent project'
inputs:
  gem_name:
    description: 'Name of the gem to update'
    required: true
  repo:
    description: 'Repository to update'
    required: true
  token:
    description: 'GitHub Personal Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout Dependent Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repo }}
        token: ${{ inputs.token }}

    - uses: sofatutor/setup-ruby@master
      with:
        ruby-version: '3.2'

    - name: Run GemDependencyUpdater Ruby Script
      shell: bash
      run: |
        ruby ${{ github.action_path }}/scripts/gem_dependency_updater.rb ${{ inputs.gem_name }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_EVENT: ${{ toJson(github.event) }}
