name: 'Gem Change Checker'
description: 'Links to the diff if a gem revision changed in a PR'
inputs:
  gem_name:
    description: 'Name of the gem to check for changes'
    required: true
    type: string
  main_branch:
    description: 'The name of the main branch'
    default: 'main'
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - uses: sofatutor/setup-ruby@master
      with:
        ruby-version: '3.2'

    - name: Run GemDependencyUpdater Ruby Script
      shell: bash
      run: |
        ruby ${{ github.action_path }}/scripts/gem_change_checker.rb ${{ inputs.gem_name }}
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
